import { pgTable, text, uuid, timestamp, boolean, integer, jsonb } from 'drizzle-orm/pg-core';
import { profiles } from './auth';
import { whatsappConversations } from './whatsapp';

export const aiAgentConfigs = pgTable('ai_agent_configs', {
  id: uuid('id').primaryKey().defaultRandom(),
  sector_id: uuid('sector_id').notNull(),
  agent_name: text('agent_name').notNull().default('AI Assistant'),
  is_enabled: boolean('is_enabled'),
  auto_reply_enabled: boolean('auto_reply_enabled'),
  response_delay_seconds: integer('response_delay_seconds'),
  max_auto_replies: integer('max_auto_replies'),
  working_hours_start: text('working_hours_start'),
  working_hours_end: text('working_hours_end'),
  working_days: integer('working_days').array(),
  working_timezone: text('working_timezone'),
  out_of_hours_message: text('out_of_hours_message'),
  welcome_message: text('welcome_message'),
  persona_description: text('persona_description'),
  tone_of_voice: text('tone_of_voice'),
  personality_traits: jsonb('personality_traits'),
  communication_style: jsonb('communication_style'),
  business_context: text('business_context'),
  product_catalog: text('product_catalog'),
  faq_context: text('faq_context'),
  custom_instructions: text('custom_instructions'),
  knowledge_base_enabled: boolean('knowledge_base_enabled'),
  learn_from_agents: boolean('learn_from_agents'),
  escalation_keywords: text('escalation_keywords').array(),
  escalation_after_minutes: integer('escalation_after_minutes'),
  escalation_on_negative_sentiment: boolean('escalation_on_negative_sentiment'),
  forbidden_topics: text('forbidden_topics').array(),
  competitor_handling: text('competitor_handling'),
  objection_style: text('objection_style'),
  upsell_enabled: boolean('upsell_enabled'),
  upsell_triggers: text('upsell_triggers').array(),
  max_discount_percent: integer('max_discount_percent'),
  created_at: timestamp('created_at').defaultNow(),
  updated_at: timestamp('updated_at').defaultNow(),
});

export const aiAgentLogs = pgTable('ai_agent_logs', {
  id: uuid('id').primaryKey().defaultRandom(),
  session_id: uuid('session_id'),
  conversation_id: uuid('conversation_id').references(() => whatsappConversations.id),
  action: text('action').notNull(),
  input_message: text('input_message'),
  ai_response: text('ai_response'),
  model_used: text('model_used'),
  tokens_used: integer('tokens_used'),
  response_time_ms: integer('response_time_ms'),
  metadata: jsonb('metadata'),
  created_at: timestamp('created_at').defaultNow(),
});

export const aiAgentSessions = pgTable('ai_agent_sessions', {
  id: uuid('id').primaryKey().defaultRandom(),
  conversation_id: uuid('conversation_id').notNull().references(() => whatsappConversations.id),
  mode: text('mode'),
  auto_reply_count: integer('auto_reply_count'),
  last_ai_response_at: timestamp('last_ai_response_at'),
  detected_intent: text('detected_intent'),
  lead_score: integer('lead_score'),
  conversation_summary: text('conversation_summary'),
  handoff_requested_at: timestamp('handoff_requested_at'),
  handoff_summary: text('handoff_summary'),
  handoff_context: jsonb('handoff_context'),
  escalated_at: timestamp('escalated_at'),
  escalated_to: uuid('escalated_to').references(() => profiles.id),
  escalation_reason: text('escalation_reason'),
  escalation_priority: integer('escalation_priority'),
  created_at: timestamp('created_at').defaultNow(),
  updated_at: timestamp('updated_at').defaultNow(),
});

export const aiResponseFeedback = pgTable('ai_response_feedback', {
  id: uuid('id').primaryKey().defaultRandom(),
  log_id: uuid('log_id').references(() => aiAgentLogs.id),
  conversation_id: uuid('conversation_id'),
  feedback_type: text('feedback_type'),
  rating: integer('rating'),
  corrected_response: text('corrected_response'),
  correction_reason: text('correction_reason'),
  given_by: uuid('given_by').references(() => profiles.id),
  created_at: timestamp('created_at').defaultNow(),
});

export const businessKnowledgeBase = pgTable('business_knowledge_base', {
  id: uuid('id').primaryKey().defaultRandom(),
  sector_id: uuid('sector_id'),
  title: text('title').notNull(),
  category: text('category').notNull(),
  subcategory: text('subcategory'),
  content: text('content').notNull(),
  keywords: text('keywords').array(),
  source: text('source'),
  parent_id: uuid('parent_id'),
  is_active: boolean('is_active'),
  is_verified: boolean('is_verified'),
  verified_by: uuid('verified_by').references(() => profiles.id),
  confidence_score: integer('confidence_score'),
  usage_count: integer('usage_count'),
  last_used_at: timestamp('last_used_at'),
  version: integer('version'),
  created_by: uuid('created_by').references(() => profiles.id),
  created_at: timestamp('created_at').defaultNow(),
  updated_at: timestamp('updated_at').defaultNow(),
});

export const responseTemplates = pgTable('response_templates', {
  id: uuid('id').primaryKey().defaultRandom(),
  sector_id: uuid('sector_id'),
  name: text('name').notNull(),
  description: text('description'),
  category: text('category'),
  template_content: text('template_content').notNull(),
  variables: jsonb('variables'),
  trigger_patterns: text('trigger_patterns').array(),
  intent_match: text('intent_match').array(),
  is_active: boolean('is_active'),
  priority: integer('priority'),
  usage_count: integer('usage_count'),
  success_rate: integer('success_rate'),
  avg_sentiment_after: integer('avg_sentiment_after'),
  created_by: uuid('created_by').references(() => profiles.id),
  created_at: timestamp('created_at').defaultNow(),
  updated_at: timestamp('updated_at').defaultNow(),
});

export const learningExamples = pgTable('learning_examples', {
  id: uuid('id').primaryKey().defaultRandom(),
  sector_id: uuid('sector_id'),
  conversation_id: uuid('conversation_id').references(() => whatsappConversations.id),
  message_id: uuid('message_id'),
  input_context: text('input_context').notNull(),
  ideal_response: text('ideal_response').notNull(),
  scenario_type: text('scenario_type'),
  tags: text('tags').array(),
  quality_score: integer('quality_score'),
  customer_satisfied: boolean('customer_satisfied'),
  lead_converted: boolean('lead_converted'),
  marked_as_good_by: uuid('marked_as_good_by').references(() => profiles.id),
  marked_at: timestamp('marked_at'),
  times_referenced: integer('times_referenced'),
  notes: text('notes'),
  created_at: timestamp('created_at').defaultNow(),
});

export const escalationQueue = pgTable('escalation_queue', {
  id: uuid('id').primaryKey().defaultRandom(),
  conversation_id: uuid('conversation_id').notNull().references(() => whatsappConversations.id),
  instance_id: uuid('instance_id'),
  sector_id: uuid('sector_id'),
  escalation_reason: text('escalation_reason').notNull(),
  priority: integer('priority'),
  status: text('status').notNull(),
  ai_summary: text('ai_summary'),
  detected_intent: text('detected_intent'),
  customer_sentiment: text('customer_sentiment'),
  lead_score: integer('lead_score'),
  assigned_to: uuid('assigned_to').references(() => profiles.id),
  assigned_at: timestamp('assigned_at'),
  resolved_at: timestamp('resolved_at'),
  resolution_notes: text('resolution_notes'),
  expires_at: timestamp('expires_at'),
  created_at: timestamp('created_at').defaultNow(),
  updated_at: timestamp('updated_at').defaultNow(),
});

export const escalationNotifications = pgTable('escalation_notifications', {
  id: uuid('id').primaryKey().defaultRandom(),
  escalation_id: uuid('escalation_id').notNull().references(() => escalationQueue.id),
  user_id: uuid('user_id').notNull().references(() => profiles.id),
  notification_type: text('notification_type').notNull(),
  read_at: timestamp('read_at'),
  dismissed_at: timestamp('dismissed_at'),
  created_at: timestamp('created_at').defaultNow(),
});

export const escalationDistributionConfig = pgTable('escalation_distribution_config', {
  id: uuid('id').primaryKey().defaultRandom(),
  sector_id: uuid('sector_id').notNull(),
  distribution_method: text('distribution_method').notNull(),
  auto_assign_enabled: boolean('auto_assign_enabled'),
  max_concurrent_escalations_per_agent: integer('max_concurrent_escalations_per_agent'),
  max_queue_time_minutes: integer('max_queue_time_minutes'),
  priority_boost_after_minutes: integer('priority_boost_after_minutes'),
  created_at: timestamp('created_at').defaultNow(),
  updated_at: timestamp('updated_at').defaultNow(),
});
