import { pgTable, text, uuid, timestamp, boolean, integer, jsonb } from 'drizzle-orm/pg-core';
import { profiles } from './auth';
import { leads } from './leads';
import { whatsappContacts, whatsappConversations } from './whatsapp';

export const schedulingConfig = pgTable('scheduling_config', {
  id: uuid('id').primaryKey().defaultRandom(),
  sector_id: uuid('sector_id'),
  is_enabled: boolean('is_enabled'),
  allow_ai_scheduling: boolean('allow_ai_scheduling'),
  default_duration_minutes: integer('default_duration_minutes'),
  slot_interval_minutes: integer('slot_interval_minutes'),
  buffer_before_minutes: integer('buffer_before_minutes'),
  buffer_after_minutes: integer('buffer_after_minutes'),
  min_advance_hours: integer('min_advance_hours'),
  max_advance_days: integer('max_advance_days'),
  require_confirmation: boolean('require_confirmation'),
  auto_cancel_no_confirmation_hours: integer('auto_cancel_no_confirmation_hours'),
  confirmation_message: text('confirmation_message'),
  default_meeting_type: text('default_meeting_type'),
  allowed_meeting_types: text('allowed_meeting_types').array(),
  google_calendar_sync: boolean('google_calendar_sync'),
  send_reminder_24h: boolean('send_reminder_24h'),
  send_reminder_1h: boolean('send_reminder_1h'),
  reminder_message_24h: text('reminder_message_24h'),
  reminder_message_1h: text('reminder_message_1h'),
  custom_reminder_hours: integer('custom_reminder_hours'),
  created_at: timestamp('created_at').defaultNow(),
  updated_at: timestamp('updated_at').defaultNow(),
});

export const availabilitySlots = pgTable('availability_slots', {
  id: uuid('id').primaryKey().defaultRandom(),
  agent_id: uuid('agent_id').references(() => profiles.id),
  sector_id: uuid('sector_id'),
  slot_type: text('slot_type'),
  day_of_week: integer('day_of_week'),
  specific_date: timestamp('specific_date'),
  start_time: text('start_time').notNull(),
  end_time: text('end_time').notNull(),
  timezone: text('timezone'),
  max_concurrent_meetings: integer('max_concurrent_meetings'),
  is_active: boolean('is_active'),
  created_at: timestamp('created_at').defaultNow(),
});

export const meetingSchedules = pgTable('meeting_schedules', {
  id: uuid('id').primaryKey().defaultRandom(),
  title: text('title').notNull(),
  description: text('description'),
  scheduled_at: timestamp('scheduled_at').notNull(),
  duration_minutes: integer('duration_minutes'),
  timezone: text('timezone'),
  meeting_type: text('meeting_type'),
  meeting_link: text('meeting_link'),
  location: text('location'),
  contact_id: uuid('contact_id').references(() => whatsappContacts.id),
  conversation_id: uuid('conversation_id').references(() => whatsappConversations.id),
  lead_id: uuid('lead_id').references(() => leads.id),
  sector_id: uuid('sector_id'),
  assigned_agent_id: uuid('assigned_agent_id').references(() => profiles.id),
  ai_session_id: uuid('ai_session_id'),
  status: text('status'),
  confirmed_at: timestamp('confirmed_at'),
  completed_at: timestamp('completed_at'),
  cancelled_at: timestamp('cancelled_at'),
  cancellation_reason: text('cancellation_reason'),
  reminder_24h_sent: boolean('reminder_24h_sent'),
  reminder_1h_sent: boolean('reminder_1h_sent'),
  reminder_custom_sent: boolean('reminder_custom_sent'),
  notes: text('notes'),
  metadata: jsonb('metadata'),
  created_by: uuid('created_by'),
  created_at: timestamp('created_at').defaultNow(),
  updated_at: timestamp('updated_at').defaultNow(),
});

export const schedulingIntents = pgTable('scheduling_intents', {
  id: uuid('id').primaryKey().defaultRandom(),
  conversation_id: uuid('conversation_id').references(() => whatsappConversations.id),
  ai_session_id: uuid('ai_session_id'),
  intent_type: text('intent_type'),
  status: text('status'),
  detected_at: timestamp('detected_at'),
  meeting_purpose: text('meeting_purpose'),
  preferred_dates: jsonb('preferred_dates'),
  duration_requested: integer('duration_requested'),
  offered_slots: jsonb('offered_slots'),
  selected_slot_index: integer('selected_slot_index'),
  resulting_meeting_id: uuid('resulting_meeting_id').references(() => meetingSchedules.id),
  confidence: integer('confidence'),
  expires_at: timestamp('expires_at'),
  created_at: timestamp('created_at').defaultNow(),
  updated_at: timestamp('updated_at').defaultNow(),
});
